### ISSUE TITLE
The ECOMMERCE_PAYMENT_PROCESSORS  tutor setting is not flexible.

### ISSUE THREAD

**Issue by Jacatove** [Pearson-Advance/tutor-ecommerce#2]
The `PAYMENT_PROCESSOR_CONFIG` configuration is grouped by the partner as you will see in the following definition with 2 partners and 2 payment processors for each partner.
```
PAYMENT_PROCESSOR_CONFIG = {
    'partner1': {
        'cybersource-rest': { ... },
        'paypal': { ... },
    },
    'partner2': {
        'paypal': { ... },
        'stripe': { ... },
    },
}
```

With Tutor, it comes with the `ECOMMERCE_PAYMENT_PROCESSORS` which is meant to configure the payment processors. However, it is used only with two hardcoded partners, `openedx` and `dev` as you will be able to see here:
https://github.com/Pearson-Advance/tutor-ecommerce/blob/e03702517f3b67daf66192b77db71c7735f8bba7/tutorecommerce/templates/ecommerce/apps/ecommerce/settings/partials/common.py#L84-L87.

This behavior avoids any other partner, which is a conflict to our needs.
@Squirrel18  FYI

**Comment by Squirrel18** [comment]
This is not an issue. To define the payment processors you should use: https://github.com/Pearson-Advance/tutor-ecommerce/blob/pearson-release/olive.main/tutorecommerce/templates/ecommerce/apps/ecommerce/settings/partials/common.py#L94 @Jacatove
